# Generated by Django 3.1.2 on 2021-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile_no',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
