# Generated by Django 3.1.2 on 2021-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20210219_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchayath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_panchayath', models.CharField(max_length=32)),
                ('panchayath_population', models.CharField(max_length=50)),
                ('panchayath_state', models.CharField(max_length=50)),
                ('panchayath_district', models.CharField(max_length=50)),
                ('panchayath_name', models.CharField(max_length=50)),
            ],
        ),
    ]
