# Generated by Django 3.1.2 on 2021-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_phnumber',
        ),
        migrations.AddField(
            model_name='person',
            name='user_username',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
