# Generated by Django 3.1.2 on 2021-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_auto_20210219_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
